name: Build IaC

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  allFiles: ${{ github.event_name != 'pull_request' || ( github.base_ref == 'main') }}

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  build:
    environment: Azure
    permissions:
      contents: read
      id-token: write
      actions: read
    name:  Build IaC
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - uses: maikvandergaag/action-biceplint@main
        id: lint
        with:
          allfiles: ${{ env.allFiles }}
          create-sarif: false
          markdown-report: false
      - uses: actions/upload-artifact@v4
        name: Upload IaC artifacts
        with:
          name: iac
          path: |
            ${{ github.workspace }}/**/*.bicep
            ${{ github.workspace }}/**/*.bicepparam