name: Deploy to Azure
run-name: Deploy to Azure - ${{ inputs.workflow_run_id == '' && 'latest' || inputs.workflow_run_id }}

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'Workflow run ID'
        required: false
        type: string

jobs:
  deploy:
    environment: Azure
    name: Deploy to Azure
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - name: Download ${{ inputs.workflow_run_id }} artifact
        if: ${{ inputs.workflow_run_id != '' }}
        id: download-artifact-workflow-app
        uses: dawidd6/action-download-artifact@v11
        with:
            github_token: ${{ github.token}}
            workflow: build-iac.yml
            workflow_conclusion: success
            branch: ${{ github.head_ref }}
            name: iac
            run_id: ${{ inputs.workflow_run_id }}
            path: myapp
      - name: Download latest artifact
        if: ${{ inputs.workflow_run_id == '' }}
        id: download-artifact-latest-app
        uses: dawidd6/action-download-artifact@v11
        with:
            github_token: ${{ github.token}}
            workflow: build-iac.yml
            workflow_conclusion: success
            branch: ${{ github.head_ref }}
            name: iac
            path: myapp
      - name: deploy
        id: deploytemp
        uses: azure/bicep-deploy@v2
        with:
          type: 'deployment'
          name: 'bicep-deployment-from-github'
          resource-group-name: rg-github-action-deploy
          scope: 'resourceGroup'
          operation: 'create'
          location: 'westeurope'
          subscription-id:  ${{ secrets.SUBSCRIPTION_ID }}
          template-file: ./08-Loops/main.bicep
          parameters-file: ./08-Loops/main.bicepparam